"""users table password_has to passwordHash

Revision ID: b185be1e89ef
Revises: ed15168ef1f5
Create Date: 2021-12-24 19:12:28.084960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b185be1e89ef'
down_revision = 'ed15168ef1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordHash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_has')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_has', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'passwordHash')
    # ### end Alembic commands ###
